name: Bug Report
description: Report a bug or unexpected behavior
labels: [ "bug" ]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: When I publish a message to a topic, I get an error...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Configure Pub/Sub with...
        2. Create a topic with...
        3. Publish a message using...
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: The message should be published successfully...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: Instead, I received an exception...
    validations:
      required: true

  - type: textarea
    id: config
    attributes:
      label: Configuration
      description: Your Pub/Sub configuration (remove sensitive data)
      render: php
      placeholder: |
        // config/pubsub.php
        'project_id' => 'my-project',
        'auth_method' => 'key_file',
        // ...

  - type: textarea
    id: code
    attributes:
      label: Code Sample
      description: Minimal code to reproduce the issue
      render: php
      placeholder: |
        use SysMatter\GooglePubSub\Facades\PubSub;

        PubSub::publish('my-topic', ['data' => 'test']);

  - type: input
    id: php-version
    attributes:
      label: PHP Version
      placeholder: "8.4"
    validations:
      required: true

  - type: input
    id: laravel-version
    attributes:
      label: Laravel Version
      placeholder: "12.0"
    validations:
      required: true

  - type: input
    id: package-version
    attributes:
      label: Package Version
      placeholder: "1.0.0"
    validations:
      required: true

  - type: dropdown
    id: environment
    attributes:
      label: Environment
      description: Where does this occur?
      options:
        - Local Development
        - Staging
        - Production
        - All Environments
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: Any relevant error messages or stack traces
      render: shell
      placeholder: |
        [2024-01-15 10:30:00] production.ERROR: Failed to publish...

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: This only happens when using push subscriptions...
