name: Feature Request
description: Suggest a new feature or enhancement
labels: [ "enhancement" ]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please help us understand your use case.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: I'm frustrated when I need to manually...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: I would like to be able to...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered
      placeholder: I considered using X but it doesn't work because...

  - type: textarea
    id: example
    attributes:
      label: Example Usage
      description: Show how you'd like to use this feature
      render: php
      placeholder: |
        use SysMatter\GooglePubSub\Facades\PubSub;

        // Proposed API
        PubSub::topic('orders')
            ->filter(['status' => 'pending'])
            ->subscribe('orders-processor');

  - type: dropdown
    id: use-case
    attributes:
      label: Use Case
      description: What is your primary use case?
      options:
        - Queue Processing
        - Event-Driven Architecture
        - Microservices Communication
        - Real-time Data Pipeline
        - Webhook Integration
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Critical - Blocking my work
        - High - Would significantly improve my workflow
        - Medium - Nice to have
        - Low - Just an idea
    validations:
      required: true

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be willing to contribute?
      options:
        - label: I'd be willing to submit a PR for this feature
        - label: I'd be willing to help with testing
        - label: I'd be willing to help with documentation

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples
      placeholder: Here's how AWS SQS handles this...
